services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      secrets:
        - env
    image: sabine-images
    container_name: sabine-images
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env

secrets:
  env:
    file: .env